chore(flake): bump nixpkgs-esp-dev to a public instead of private version
This bumps ESP-IDF to 5.5 from 5.4.

5.4.1 and 5.5 contain some fixes we want.

Fixes
-----

1. https://github.com/espressif/esp-idf/15167:
   undefined reference to `__atomic_test_and_set` when using
   `std::atomic_flag`.
2. https://github.com/espressif/esp-idf/commit/6d06f5fe441182a20d9d251d49353812e6d8a3f0
   fix(esp_eth): fix openeth driver to consider MAC address set in QEMU